---
title: "Case Study 09"
author: Sadie Kratt
date: November 2, 2021
output: github_document
---
```{r}
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
data(world)
data(us_states)
```

```{r}
# Download zipped data from noaa with storm track information
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"
tdir=tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir)
list.files(tdir)
```

```{r}
storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))
```

```{r}
#Filter the storms from 1950 to the present
storms_filter <- storm_data %>% 
  filter(year >= 1950) %>% 
  mutate_if(is.numeric, function(x) ifelse(x == -999.0, NA, x)) %>% 
  mutate(decade = (floor(year/10)*10)) 
#Find the bounding box of the data
region <- st_bbox(storms_filter)
```

```{r}
#Make plot
ggplot()+
  geom_sf(data=world, inherit.aes=F)+
  facet_wrap(~decade)+
  stat_bin2d(data=storms_filter, aes(y=st_coordinates(storms_filter)[,2], x=st_coordinates(storms_filter)[,1]),bins=100)+
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000))+
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)])
```
```{r}
#Calculate table of the five states with most storms
us_states<- st_transform(us_states, st_crs(storms_filter))

#Rename the NAME column
states<- us_states %>% 
  select(state=NAME)

#Join the data
storm_states <- st_join(storms_filter, states, join = st_intersects,left = F) %>%
  group_by(state) %>%
  summarize(storms_filter=length(unique(NAME))) %>%
  arrange(desc(storms_filter)) %>%
  slice(1:5)

#view table
storm_states
```


